### PR TITLE
use setpriv instead of gosu

### PR DESCRIPTION
**Pull request by jrwren**

### CODE REVIEW

**Comment by jrwren** [comment]
for #22 

This is the minimal PR which didn't run apply.sh. Please comment if you'd prefer that I run it to update the dockerfiles.

**Comment by roshkhatri** [comment]
Yes, we would prefer to update the Docker files so we can build the images.

**Comment by roshkhatri** [comment]
Please sign off the commits, wouldn't be able to merge without it

**Comment by jrwren** [comment]
I did not really understand this signoff thing so I squashed the commits to do it. Please take another look.

**Review by roshkhatri — APPROVED** [review]
The changes seems good and the image build successfully.

**Review by madolson — APPROVED** [review]

**Pull request merged**
